import { ArrowRight, CheckCircle2, CircleAlert } from 'lucide-react'; import { motion } from 'framer-motion'; import { providerCategoryLabels } from '../../data/providers'; import type { Provider } from '../../types'; import { ProviderLogo } from './ProviderLogo';
export interface ProviderActivity { count: number; preview: string; updatedAt: string }
export function ProviderCard({ provider, selected, onSelect, activity }: { provider: Provider; selected: boolean; onSelect: (provider: Provider) => void; activity?: ProviderActivity | null }) {
  const unavailable = provider.status === 'unavailable';
  const badge = provider.status === 'demo'
    ? { cls: 'border border-[#ecd7a7] bg-[#fff7e7] text-[#77541b]', icon: CircleAlert, label: 'Demo' }
    : unavailable
      ? { cls: 'border border-[#ecd7a7] bg-[#fff7e7] text-[#77541b]', icon: CircleAlert, label: 'Ntiraboneka' }
      : { cls: 'text-ejo-green', icon: CheckCircle2, label: 'Bihujwe' };
  const note = provider.status === 'demo' ? 'Demo y’igerageza — ntabwo ihujwe n’ubuyobozi nyabwo' : unavailable ? 'Turimo kubihuza' : 'Serivisi zizwi kandi zizewe';
  return <motion.article layout tabIndex={unavailable ? -1 : 0} onClick={() => !unavailable && onSelect(provider)} onKeyDown={e => { if ((e.key === 'Enter' || e.key === ' ') && !unavailable) { e.preventDefault(); onSelect(provider); } }} className={`border border-t-[3px] border-t-ejo-blue bg-white p-5 ${selected ? 'border-ejo-green shadow-[-4px_0_0_#16865B_inset]' : 'border-ejo-border'} ${unavailable ? 'bg-[#fbfcfb]' : 'cursor-pointer hover:border-ejo-green focus-visible:outline focus-visible:outline-2 focus-visible:outline-ejo-green'}`}><div className="flex items-center gap-3"><ProviderLogo id={provider.id} mark={provider.mark} category={provider.category} website={provider.website}/><div className="mr-auto min-w-0"><p className="eyebrow mb-0">{providerCategoryLabels[provider.category].toUpperCase()}</p><h3 className="truncate font-display text-lg font-bold">{provider.name}</h3></div><badge.icon className={`shrink-0 ${badge.cls.includes('text-ejo-green') ? 'text-ejo-green' : ''}`} size={13}/><span className={`flex shrink-0 items-center gap-1 text-[10px] font-bold ${badge.cls}`}>{badge.label}</span></div><p className="my-4 max-w-xl text-xs leading-5 text-ejo-muted">{provider.description}</p>{activity && <div className="mb-5 border-t border-[#e4ebea] pt-3 text-[10px] leading-4 text-ejo-muted"><strong className="block text-ejo-blue">{activity.count} ubutumwa mu kiganiro</strong><p className="mt-1 truncate">{activity.preview}</p></div>}{provider.capabilities.length > 0 && <ul className="mb-5 flex flex-wrap gap-1.5">{provider.capabilities.map(cap => <li className="border border-[#d3e5dd] bg-[#f1f7f4] px-2 py-1 text-[10px] text-[#355a50]" key={cap.id}>{cap.name}</li>)}</ul>}<div className="flex items-center justify-between gap-3 border-t border-[#e4ebea] pt-3 text-[10px] text-ejo-muted"><span>{note}</span><button disabled={unavailable} className={`inline-flex items-center gap-1 border px-3 py-2 font-display text-[11px] font-bold ${unavailable ? 'cursor-not-allowed border-[#c9d2cf] bg-ejo-canvas text-[#82908c]' : 'border-ejo-blue bg-ejo-blue text-white hover:bg-[#0d304c]'}`}>Tangira {!unavailable && <ArrowRight size={15}/>}</button></div></motion.article>;
}