export const providerNames = {
  irembo: 'Irembo',
  rssb: 'RSSB',
  rnp: 'Rwanda National Police',
  rra: 'RRA',
  rsb: 'Rwanda Standards Board',
  rdb: 'RDB',
};

export const servicesKb = [
  {
    id: 'passport',
    category: 'Serivisi za Leta',
    providerId: 'irembo',
    name: 'Passport Application',
    description: 'Gusaba icyangombwa cyo kugenda mu mahanga (passport).',
    whoCanUse: 'Abanyarwanda bose bafite indangamuntu.',
    documents: ['Indangamuntu (ID)', 'Igicapo cyo kwishyura (payment reference)'],
    infoNeeded: ['Izina ryuzuye', 'Nomero ya telefone', 'Aho uba (adresse)'],
    steps: ['Kwiyandikisha kuri Irembo', 'Kuzuza ubusabe bwa passport', 'Kwishyura igiciro cyemejwe', 'Kurikira icyemezo kuri Irembo'],
    fees: null,
    processingTime: null,
    access: 'Kuri Irembo (irembo.gov.rw)',
  },
  {
    id: 'birth-certificate',
    category: 'Inyandiko',
    providerId: 'irembo',
    name: 'Birth Certificate',
    description: 'Gusaba icyangombwa cyo kuvuka (certificat de naissance).',
    whoCanUse: 'Abanyarwanda bose bashaka icyangombwa cyabo cyo kuvuka.',
    documents: ['Indangamuntu', 'Ibyandikishije (si iki gikorwa cya mbere)'],
    infoNeeded: ['Izina ryuzuye', 'Itariki yo kuvuka', 'Aho wavukiye'],
    steps: ['Kwiyandikisha kuri Irembo', 'Kuzuza ubusabe', 'Kwishyura', 'Gukurikira icyemezo'],
    fees: null,
    processingTime: null,
    access: 'Kuri Irembo (irembo.gov.rw)',
  },
  {
    id: 'divorce-certificate',
    category: 'Inyandiko',
    providerId: 'irembo',
    name: 'Divorce Certificate',
    description: 'Gusaba icyangombwa cy\'agatanya (divorce certificate).',
    whoCanUse: 'Abashakanye batandukanye bafite icyemezo cy\'urukiko.',
    documents: ['Indangamuntu', 'Icyemezo cy\'urukiko cy\'agatanya'],
    infoNeeded: ['Izina ryuzuye', 'Amakuru y\'ubukwe', 'Nomero ya telefone'],
    steps: ['Kwiyandikisha kuri Irembo', 'Kuzuza ubusabe', 'Kwishyura', 'Gukurikira icyemezo'],
    fees: null,
    processingTime: null,
    access: 'Kuri Irembo (irembo.gov.rw)',
  },
  {
    id: 'mutuelle',
    category: 'Ubuzima',
    providerId: 'rssb',
    name: 'Mutuelle de Santé',
    description: 'Kwiyandikisha no kwishyura imisanzu ya Mutuelle de Santé.',
    whoCanUse: 'Abanyarwanda bose bishaka kwiyandikisha muri Mutuelle.',
    documents: ['Indangamuntu (ID)'],
    infoNeeded: ['Izina ryuzuye', 'Umuryango / akagari', 'Nomero ya telefone'],
    steps: ['Kugana umurenge wawe', 'Kwiyandikisha mu bafite ubwishingizi', 'Kwishyura imisanzu', 'Kubona ibyo kwerekana ubwishingizi'],
    fees: null,
    processingTime: null,
    access: 'Umurenge wawe cyangwa kuri RSSB',
  },
  {
    id: 'pension',
    category: 'Imiryango',
    providerId: 'rssb',
    name: 'Pension Request',
    description: 'Gusaba pension ya za bukuru (ubufatanye n\'imisanzu y\'umurimo).',
    whoCanUse: 'Abafite imyaka y\'ubukuru cyangwa bafite ibyangombwa by\'umurimo.',
    documents: ['Indangamuntu', 'Ibimenyetso by\'umurimo (record)'],
    infoNeeded: ['Izina ryuzuye', 'Ibyo wakoze (employer)', 'Nomero ya telefone'],
    steps: ['Kugana RSSB', 'Kuzuza ubusabe bwa pension', 'Gushyiraho inyandiko', 'Gukurikira icyemezo'],
    fees: null,
    processingTime: null,
    access: 'Ibiro bya RSSB cyangwa kuri rssb.rw',
  },
  {
    id: 'tax-registration',
    category: 'Imisoro',
    providerId: 'rra',
    name: 'Tax Registration (TIN)',
    description: 'Kwiyandikisha kugira ngo ubone TIN n\'imisoro yawe iboneke.',
    whoCanUse: 'Abantu ku giti cyabo n\'ubucuruzi bushaka TIN.',
    documents: ['Indangamuntu', 'Ibyandikishije (business)'],
    infoNeeded: ['Izina ryuzuye', 'Icyiciro cy\'umukoresha', 'Nomero ya telefone'],
    steps: ['Kugana RRA', 'Kuzuza ubusabe bwa TIN', 'Kubona TIN', 'Kwishyura imisoro ku gihe'],
    fees: null,
    processingTime: null,
    access: 'Kuri RRA (rra.gov.rw)',
  },
  {
    id: 'tax-clearance',
    category: 'Imisoro',
    providerId: 'rra',
    name: 'Tax Clearance',
    description: 'Gusaba icyemezo cyo kutagira imisoro idashyuwe (tax clearance).',
    whoCanUse: 'Abakoresha bakeneye icyangombwa cyo kutagira imisoro.',
    documents: ['Indangamuntu', 'TIN', 'Icyemezo cy\'imisoro (mbere)'],
    infoNeeded: ['Izina ryuzuye', 'Nomero ya TIN', 'Nomero ya telefone'],
    steps: ['Kugana RRA', 'Gusaba tax clearance', 'Kwishyura icyagisigaye (niba kihari)', 'Kubona icyemezo'],
    fees: null,
    processingTime: null,
    access: 'Kuri RRA (rra.gov.rw)',
  },
  {
    id: 'driving-license',
    category: 'Ubwikorezi',
    providerId: 'rnp',
    name: 'Driving License',
    description: 'Gusaba permis yo gutwara ibinyabiziga (driving license).',
    whoCanUse: 'Abantu bageze ku myaka isabwa bagomba gutwara ibinyabiziga.',
    documents: ['Indangamuntu', 'Icyemezo cy\'ubuzima', 'Ibyandikishije by\'ibizamini'],
    infoNeeded: ['Izina ryuzuye', 'Icyiciro cya permis', 'Nomero ya telefone'],
    steps: ['Kwiyandikisha mu kigo cy\'amashanyarazi cyangwa RNP', 'Kuzuza ubusabe', 'Kwishyura', 'Gukurikira igihe cya permis'],
    fees: null,
    processingTime: null,
    access: 'Ibiro bya Rwanda National Police',
  },
  {
    id: 'police-report',
    category: 'Serivisi za Leta',
    providerId: 'rnp',
    name: 'Police Report',
    description: 'Gusaba raporo ya Polisi (kubwira ibyabaye, kubura ibintu, n\'ibindi).',
    whoCanUse: 'Umuntu wese ukeneye raporo ya Polisi.',
    documents: ['Indangamuntu'],
    infoNeeded: ['Izina ryuzuye', 'Ibyabaye', 'Aho byabereye'],
    steps: ['Kugana urugomero rwa Polisi rwegereye', 'Kubwira ibyabaye', 'Kubona raporo'],
    fees: null,
    processingTime: null,
    access: 'Ibiro bya Polisi by\'ahantu',
  },
  {
    id: 'business-registration',
    category: 'Ubucuruzi',
    providerId: 'rdb',
    name: 'Business Registration',
    description: 'Kwiyandikisha ubucuruzi bushya (registration of a business).',
    whoCanUse: 'Abashaka gutangiza ubucuruzi mu Rwanda.',
    documents: ['Indangamuntu', 'Amazina ya business (2 cyangwa 3)'],
    infoNeeded: ['Izina ry\'ubucuruzi', 'Icyiciro cy\'ubucuruzi', 'Aho bizabera', 'Nomero ya telefone'],
    steps: ['Kwiyandikisha', 'Kuzuza ubusabe', 'Kwishyura', 'Kubona icyemezo cy\'ubucuruzi'],
    fees: null,
    processingTime: null,
    access: 'Kuri RDB (rdb.rw)',
  },
  {
    id: 'certificate-verification',
    category: 'Inyandiko',
    providerId: 'rsb',
    name: 'Certificate Verification',
    description: 'Kugenzura niba icyangombwa cy\'ibipimo (certificate) ari icy\'ukuri.',
    whoCanUse: 'Abashaka kwemeza niba certificate ari nyayo.',
    documents: ['Icyangombwa kigenzurwa'],
    infoNeeded: ['Nomero ya certificate', 'Icyiciro cyayo'],
    steps: ['Kugana RSB', 'Kuzuza ubusabe bwo kugenzura', 'Kubona igisubizo'],
    fees: null,
    processingTime: null,
    access: 'Kuri Rwanda Standards Board (rsb.rw)',
  },
];

export function discoverPrompt() {
  const list = servicesKb.map(s => `{id:"${s.id}", name:"${s.name}", category:"${s.category}", provider:"${providerNames[s.providerId] ?? s.providerId}"}`);
  return `Uri umuyobozi w'ibiro by'ubufasha bwa EjoFlow mu Rwanda. Izina ry'urubuga ni 'EjoFlow' gusa — ntirigomba gusemurwa cyangwa guhindurwa mu rurimi urwo ari rwo rwose (ntiwandike 'Tomorrow Flow'). Umukoresha asobanura mu magambo ye gusa icyo ashatse gukora — ntibikenewe ko amenyera serivisi cyangwa ikigo.
Umurimo wawe: kumva icyo ashatse, ugahitamo serivisi ivuguruzanya n'urutonde rw'amaserivisi yemejwe.
Usubize JSON gusa, nta kandi kintu:
{"understanding":"igisubizo kigufi mu Kinyarwanda","confidence":"high","serviceId":"id cyangwa null","clarification":[],"category":"icyiciro"}
Amabwiriza:
- understanding: igisubizo kigufi cy'icyo umukoresha ashatse, kitagira amagambo y'itekiniki, gitangira na "Ndumva ushaka".
- Iyo uhitamo serviceId, igomba kuba iri mu rutonde rw'amaserivisi yemejwe.
- Iyo utabonye serivisi ihuye (serviceId null), shyiramo mu "clarification" amahitamo ahujwe n'icyo yashatse (kugeza 3, buri wese mu Kinyarwanda, akubwa ku murongo). Ntukarimbane ibitazi.
- category: "Serivisi za Leta" | "Ubuzima" | "Inyandiko" | "Imisoro" | "Imiryango" | "Ubucuruzi" | "Imirimo" | "Ubwikorezi" | "Ibindi".
Ama serivisi yemejwe: [${list.join(', ')}]`;
}