import { ChevronRight, LoaderCircle, MessageSquareText } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ProviderLogo } from '../components/providers/ProviderLogo';
import { providers } from '../data/providers';
import { memoryService, timeAgo, type ConversationSummary } from '../services/memoryService';
const providerById = new Map(providers.map(p => [p.id, p]));
export function ConversationsPage() {
  const [convs, setConvs] = useState<ConversationSummary[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { memoryService.conversations().then(c => { setConvs(c); setLoading(false); }); }, []);
  return <main className="mx-auto max-w-[1120px] px-4 py-8 md:px-10 md:py-12"><header className="mb-8"><p className="eyebrow">IBIGANIRO</p><h2 className="font-display text-2xl font-bold">Ibiganiro byawe</h2><p className="mt-2 text-sm text-ejo-muted">Komeza ibiganiro byatanzwe na EjoChat — byose biribukwa.</p></header>{loading ? <div className="flex items-center gap-2 py-10 text-xs text-ejo-muted"><LoaderCircle className="animate-spin text-ejo-green" size={15}/> Turimo gutanga ibiganiro…</div> : convs.length === 0 ? <section className="border border-dashed border-[#b9c9c4] bg-white p-10 text-center"><MessageSquareText className="mx-auto text-ejo-green" size={26}/><h3 className="mt-4 font-display text-lg font-bold">Nta biganiro bihari</h3><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-ejo-muted">Ibiganiro byawe na EjoChat bizerekwa hano. Tangira icya mbere ubu!</p><Link to="/app" className="mt-5 inline-flex items-center gap-1 border border-ejo-blue bg-ejo-blue px-4 py-2.5 font-display text-xs font-bold text-white hover:bg-[#0d304c]">Tangira ikiganiro<ChevronRight size={15}/></Link></section> : <ul className="space-y-3">{convs.map(c => { const p = providerById.get(c.provider_id); return <li key={c.id}><Link to={`/app/ibiganiro/${c.provider_id}`} className="flex items-center gap-4 border border-ejo-border bg-white p-4 hover:border-ejo-green focus-visible:outline focus-visible:outline-2 focus-visible:outline-ejo-green">{p ? <ProviderLogo id={p.id} mark={p.mark} category={p.category} website={p.website}/> : <span className="grid size-10 place-items-center rounded-sm bg-[#52616B] text-white"><span className="font-display font-extrabold">C</span></span>}<div className="min-w-0 flex-1"><strong className="block font-display text-sm">{p?.name ?? 'EjoChat'}</strong>{c.last_message ? <p className="mt-1 truncate text-xs text-ejo-muted">{c.last_message}</p> : <p className="mt-1 text-xs text-ejo-muted">Ibiganiro bwatangiye, ubutumwa bukurikira.</p>}</div><span className="shrink-0 text-right text-[10px] leading-4 text-ejo-muted">{timeAgo(c.updated_at)}<small className="mt-0.5 block font-bold text-ejo-blue">{c.message_count} ubutumwa · {c.action_count} ibikorwa</small></span><ChevronRight size={16} className="shrink-0 text-ejo-green"/></Link></li>; })}</ul>}</main>;
}