import { Check, ChevronDown, CircleAlert, FileText, HeartPulse, LoaderCircle, Send } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion'; import { useEffect, useState } from 'react'; import { useNavigate, useParams } from 'react-router-dom';
import { ProviderLogo } from '../components/providers/ProviderLogo';
import { mockProviderService } from '../services/mock/mockProviderService';
import { useConversation, type ConversationItem } from '../hooks/useConversation';
import type { Provider } from '../types';
const path = ['Sobanukirwa', 'Amakuru', 'Isuzuma', 'Emeza', 'Byarangiye'];
function ProviderContext({ provider, mutuelle }: { provider: Provider; mutuelle?: boolean }) {
  return <aside className="border-b border-ejo-border bg-white p-5 lg:border-b-0 lg:border-r"><p className="eyebrow">UMUYOBORO</p><div className="mt-2 flex items-center gap-3"><ProviderLogo id={provider.id} mark={provider.mark} website={provider.website} size="md"/><span><strong className="block font-display text-lg">{provider.name}</strong><small className="text-[10px] text-ejo-muted">{provider.domain}</small></span></div>{mutuelle && <div className="mt-6 hidden border-t border-ejo-border pt-4 lg:block"><p className="eyebrow">URI GUKORAHO</p><p className="mt-2 flex items-center gap-2 text-xs font-semibold text-ejo-blue"><HeartPulse size={16}/> Mutuelle</p><p className="mt-2 text-[11px] leading-5 text-ejo-muted">EjoFlow izakwereka amakuru akenewe, intambwe ku yindi.</p></div>}</aside>;
}
function ServicePath({ phase }: { phase: string }) { const active = phase === 'question' ? 0 : phase === 'processing' ? 1 : 2; return <aside className="border-t border-ejo-border bg-white p-5 lg:border-l lg:border-t-0"><p className="eyebrow">URUGENDO RWA SERIVISI</p><h3 className="font-display text-base font-bold">Uko icyifuzo kigeze</h3><ol className="mt-5">{path.map((step, index) => { const done = index < active; const isActive = index === active; return <li className="relative flex min-h-14 gap-3 after:absolute after:left-[13px] after:top-7 after:h-6 after:w-px after:bg-ejo-border last:after:hidden" key={step}><span className={`grid size-7 place-items-center rounded-full border text-[11px] font-bold ${done ? 'border-ejo-green bg-ejo-green text-white' : isActive ? 'border-ejo-green bg-[#f1f7f4] text-ejo-green ring-4 ring-[#dcece5]' : 'border-[#bfcfca] bg-white text-ejo-muted'}`}>{done ? <Check size={13}/> : index + 1}</span><span><strong className="block text-xs">{step}</strong><small className="block text-[10px] text-ejo-muted">{isActive ? 'Ubu ni ho uri' : index === 3 ? 'Banza usuzume' : 'Tuzakuyobora'}</small></span>{index === 3 && phase !== 'review' && <CircleAlert className="ml-auto text-ejo-amber" size={15}/>}</li>; })}</ol><div className="mt-7 border-t border-ejo-border pt-4 text-[10px] leading-4 text-ejo-muted"><strong className="text-ejo-ink">Amakuru ararinzwe</strong><br/>Nta bwishyu bwoherezwa utabyemeje.</div></aside>; }
function MessageView({ item, onReview, botName = 'EjoFlow' }: { item: ConversationItem; onReview: () => void; botName?: string }) {
  if (item.type === 'action') return <motion.section initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="border border-ejo-border border-t-[3px] border-t-ejo-green bg-white"><div className="flex items-center justify-between border-b border-ejo-border px-4 py-3"><span><p className="eyebrow mb-0">IGIKORWA CYABONETSE</p><h3 className="font-display text-base font-bold">Mutuelle</h3></span><span className="flex items-center gap-1 text-[10px] font-bold text-ejo-green"><Check size={13}/> Iteguriwe gusuzumwa</span></div><dl className="grid grid-cols-2 px-4 py-4 text-xs"><div><dt className="text-ejo-muted">Abantu</dt><dd className="mt-1 font-bold">{item.people}</dd></div><div><dt className="text-ejo-muted">Igikorwa</dt><dd className="mt-1 font-bold">{item.action?.label ?? 'Kwishyura Mutuelle'}</dd></div><div><dt className="text-ejo-muted">Intambwe ikurikira</dt><dd className="mt-1 font-bold">Reba mbere</dd></div></dl><div className="border-t border-ejo-border p-3"><button onClick={onReview} className="inline-flex items-center gap-1 bg-ejo-blue px-3 py-2 text-xs font-bold text-white">Reba mbere yo kwishyura <FileText size={14}/></button></div></motion.section>;
  const style = item.type === 'user' ? 'ml-auto max-w-md bg-ejo-blue text-white' : item.type === 'error' ? 'border-l-[3px] border-ejo-error bg-[#fff5f5] text-[#722525]' : item.type === 'question' ? 'border-l-[3px] border-l-ejo-green bg-white' : 'border border-ejo-border bg-white';
  return <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className={`max-w-md p-3 text-xs leading-5 ${style}`}>{item.type !== 'user' && item.type !== 'error' && <strong className="mb-1 block text-[10px] text-ejo-green">{botName}</strong>}{item.text}</motion.div>;
}
export function ConversationWorkspacePage() {
  const { providerId = 'irembo' } = useParams(); const navigate = useNavigate();
  const [provider, setProvider] = useState<Provider | null>(null);
  useEffect(() => { mockProviderService.getById(providerId).then(p => { if (p) setProvider(p); }); }, [providerId]);
  const { items, phase, typing, answer } = useConversation(providerId, provider?.name ?? providerId.charAt(0).toUpperCase() + providerId.slice(1));
  const [input, setInput] = useState(''); const [providerOpen, setProviderOpen] = useState(false), [pathOpen, setPathOpen] = useState(false);
  function send() { answer(input); setInput(''); }
  function review(item: ConversationItem) { if (item.people) navigate(`/app/gusuzuma/mutuelle?abantu=${item.people}`); }
  if (!provider) return <main className="mx-auto max-w-[1440px] px-4 py-10 lg:grid lg:grid-cols-[220px_minmax(0,1fr)_260px]"><div className="hidden lg:block"><div className="h-64 animate-pulse border border-ejo-border bg-white"/></div><div className="h-96 animate-pulse border border-ejo-border bg-white"/><div className="hidden lg:block"><div className="h-64 animate-pulse border border-ejo-border bg-white"/></div></main>;
  const botName = provider.id === 'irembo' ? 'EjoFlow' : provider.name + ' · EjoFlow';
  return <main className="mx-auto min-h-[calc(100vh-72px)] max-w-[1440px] lg:grid lg:grid-cols-[220px_minmax(0,1fr)_260px]"><div className="lg:hidden"><button onClick={() => setProviderOpen(!providerOpen)} className="flex w-full items-center justify-between border-b border-ejo-border bg-white px-4 py-3 text-left"><span className="flex items-center gap-2"><ProviderLogo id={provider.id} mark={provider.mark} website={provider.website} size="sm"/><span><strong className="block text-sm">{provider.name}</strong><small className="block text-[10px] text-ejo-muted">{provider.domain}</small></span></span><ChevronDown size={17}/></button>{providerOpen && <ProviderContext provider={provider} mutuelle={provider.id === 'irembo'}/>}</div><div className="hidden lg:block"><ProviderContext provider={provider} mutuelle={provider.id === 'irembo'}/></div><section className="flex min-h-[620px] flex-col bg-ejo-canvas"><header className="border-b border-ejo-border bg-white px-5 py-4"><p className="eyebrow">IKIGANIRO CYA SERIVISI</p><h2 className="font-display text-lg font-bold">{provider.id === 'irembo' ? 'Kwishyura Mutuelle' : `Ikiganiro na ${provider.name}`}</h2><p className="mt-1 text-[11px] text-ejo-muted">Sobanura kimwe gusa; tuzakubaza ikindi gikenewe.</p></header><div className="flex-1 space-y-5 overflow-y-auto px-5 py-6 md:px-8"><AnimatePresence initial={false}>{items.map(item => <MessageView item={item} key={item.id} onReview={() => review(item)} botName={botName}/>)}</AnimatePresence>{typing && <div className="flex items-center gap-2 text-xs text-ejo-muted"><LoaderCircle className="animate-spin text-ejo-green" size={15}/> EjoFlow irategura amakuru…</div>}</div><footer className="border-t border-ejo-border bg-white p-3"><label className="flex items-end gap-2 border border-[#a9bdb6] border-l-[3px] border-l-ejo-green bg-white p-2"><textarea value={input} onChange={e => setInput(e.target.value)} rows={2} placeholder={provider.id === 'irembo' ? 'Andika umubare w’abantu…' : `Andika icyo ushaka gukora na ${provider.name}…`} className="w-full resize-none bg-transparent text-xs outline-none"/><button onClick={send} disabled={!input.trim()} aria-label="Ohereza" className="grid size-8 shrink-0 place-items-center bg-ejo-green text-white disabled:cursor-not-allowed disabled:bg-[#a8b8b3]"><Send size={15}/></button></label></footer></section><div className="hidden lg:block"><ServicePath phase={phase}/></div></main>;
}