import { CircleHelp, Lock, MessageSquareText, ShieldCheck, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
const steps = [
  { icon: MessageSquareText, title: 'Sobanura icyo ushaka', text: 'Andika mu Kinyarwanda cyangwa mu Cyongereza — nk\'"mbone imenyesha zanjye" cyangwa "ndashaka kumenya imisoro yanjye".' },
  { icon: Sparkles, title: 'EjoChat ikora n\'umuyoboro wawe', text: 'EjoChat ibona amakuru aturuka mu muyoboro wahisemo (nk\'imeli za Gmail) ikayagushyira mu rurimi rw\'ibinyabuzima.' },
  { icon: ShieldCheck, title: 'Emeza mbere yo gukora', text: 'Nta bwishyu, nta cyo woherezwa utabyemeje. Ibintu by\'ingenzi bigusabwa kwemeza mbere.' },
];
const faqs = [
  { q: 'EjoChat ibona amakuru yanjye ite?', a: 'EjoChat ikora gusa n\'umuyoboro wahisemo (provider), ikayaguha amakuru ahari aho. Nta makuru y\'inyongera aturuka ahandi.' },
  { q: 'Amakuru yanjye ararinzwe?', a: 'Yego. Ibiganiro byawe biribukwa kuri EjoFlow kugira ngo ukomeze aho warekiye, kandi nta makuru yoherezwa utabyemeje.' },
  { q: 'Nshobora gukora ubwishyu binyuze muri EjoFlow?', a: 'Ubwishyu bw\'ubuyobozi bugusabwa kwemeza buri gihe. EjoChat izakuyobora intambwe ku yindi utabishaka ku gahato.' },
  { q: 'EjoChat yansubije mu Cyongereza, nshaka Kinyarwanda?', a: 'Andika "subiza mu Kinyarwanda" cyangwa utangize ubutumwa bwawe mu Kinyarwanda — EjoChat izakurikira ururimi ukoresha.' },
];
export function HelpPage() {
  return <main className="mx-auto max-w-[1120px] px-4 py-8 md:px-10 md:py-12"><header className="mb-8"><p className="eyebrow">UBUFASHA</p><h2 className="font-display text-2xl font-bold">Ubufasha</h2><p className="mt-2 text-sm text-ejo-muted">Uko EjoChat ikora, n\'ibibazo bikunze kubazwa.</p></header><section className="mb-8 grid gap-3 md:grid-cols-3">{steps.map((s, i) => <article className="border border-t-[3px] border-t-ejo-green bg-white p-5" key={s.title}><s.icon className="text-ejo-green" size={20}/><h3 className="mt-3 font-display text-sm font-bold"><span className="mr-1 text-ejo-green">{i + 1}.</span>{s.title}</h3><p className="mt-2 text-xs leading-5 text-ejo-muted">{s.text}</p></article>)}</section><section className="border border-ejo-border bg-white p-6"><h3 className="flex items-center gap-2 font-display text-base font-bold"><CircleHelp className="text-ejo-green" size={18}/> Ibibazo bikunze kubazwa</h3><div className="mt-4 divide-y divide-ejo-border">{faqs.map(f => <details className="group py-3" key={f.q}><summary className="cursor-pointer list-none text-xs font-bold text-ejo-ink marker:hidden group-open:text-ejo-blue">{f.q}</summary><p className="mt-2 text-xs leading-5 text-ejo-muted">{f.a}</p></details>)}</div></section><section className="mt-6 flex flex-col items-start justify-between gap-4 border border-[#d3e5dd] bg-[#f1f7f4] p-5 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><Lock className="shrink-0 text-ejo-green" size={18}/><p className="text-xs leading-5 text-[#355a50]"><strong className="block text-sm">Ukeneye ubundi bufasha?</strong>Andika ubutumwa kuri EjoChat, tuzakuyobora intambwe ku yindi.</p></div><Link to="/app/ibiganiro/ejochat" className="shrink-0 border border-ejo-blue bg-ejo-blue px-4 py-2.5 font-display text-xs font-bold text-white hover:bg-[#0d304c]">Ganira na EjoChat</Link></section></main>;
}