import { Briefcase, ChevronRight, MessageSquareText, Sparkles } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { ProviderLogo } from '../components/providers/ProviderLogo';
import { providers } from '../data/providers';
import { useI18n } from '../i18n/LanguageContext';
const assistants = [
  { id: 'ejochat', tagline: 'mywork.tag.ejochat', suggestions: ['mywork.sug.e1', 'mywork.sug.e2', 'mywork.sug.e3'] },
  { id: 'gmail', tagline: 'mywork.tag.gmail', suggestions: ['mywork.sug.g1', 'mywork.sug.g2', 'mywork.sug.g3'] },
  { id: 'whatsapp', tagline: 'mywork.tag.whatsapp', suggestions: ['mywork.sug.w1', 'mywork.sug.w2', 'mywork.sug.w3'] },
  { id: 'tasks', tagline: 'mywork.tag.tasks', suggestions: ['mywork.sug.t1', 'mywork.sug.t2', 'mywork.sug.t3'] },
];
const byId = new Map(providers.map(p => [p.id, p]));
export function MyWorkPage() {
  const navigate = useNavigate();
  const { t } = useI18n();
  return <main className="mx-auto max-w-[1120px] px-4 py-8 md:px-10 md:py-12"><header className="flex flex-wrap items-start justify-between gap-4"><div className="max-w-2xl"><p className="eyebrow">{t('mywork.eyebrow')}</p><h1 className="mt-2 flex items-center gap-3 font-display text-3xl font-extrabold tracking-tight md:text-4xl"><span className="grid size-11 place-items-center rounded-lg bg-ejo-blue text-white"><Briefcase size={22}/></span>{t('nav.myWork')}</h1><p className="mt-3 max-w-xl text-sm leading-6 text-ejo-muted">{t('mywork.subtitle')}</p></div></header><section className="mt-8 grid grid-cols-1 gap-4 md:grid-cols-2"><div className="section-heading md:col-span-2"><div><p className="eyebrow">{t('mywork.sectionEyebrow')}</p><h3>{t('mywork.sectionTitle')}</h3></div></div>{assistants.map(a => { const p = byId.get(a.id); if (!p) return null; const connected = p.status === 'connected'; return <article className="flex flex-col border border-ejo-border bg-white p-6 hover:border-ejo-green" key={a.id}><div className="flex items-start gap-4"><ProviderLogo id={p.id} mark={p.mark} category={p.category} website={p.website} size="lg"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-display text-lg font-bold">{p.name}</h3>{connected ? <span className="rounded-full bg-[#dcece5] px-2 py-0.5 text-[9px] font-bold text-ejo-green">{t('mywork.connected')}</span> : <span className="rounded-full bg-[#fdf3dc] px-2 py-0.5 text-[9px] font-bold text-[#9a6a00]">DEMO</span>}</div><p className="mt-1 text-xs leading-5 text-ejo-muted">{t(a.tagline)}</p></div></div><ul className="mt-4 flex flex-wrap gap-1.5">{p.capabilities.map(cap => <li className="rounded-sm bg-ejo-canvas px-2 py-1 text-[10px] font-semibold text-ejo-blue" key={cap.id}>{cap.name}</li>)}</ul><div className="mt-5 border-t border-ejo-border pt-4"><p className="eyebrow">{t('mywork.try')}</p><div className="mt-2 space-y-1.5">{a.suggestions.map(s => <button onClick={() => navigate(`/app/ibiganiro/${a.id}?q=${encodeURIComponent(t(s))}`)} className="flex w-full items-center gap-2 border border-ejo-border bg-ejo-canvas px-3 py-2 text-left text-xs font-semibold text-ejo-ink hover:border-ejo-green hover:text-ejo-blue" key={s}><Sparkles size={13} className="shrink-0 text-ejo-green"/>{t(s)}</button>)}</div></div><div className="mt-5 flex items-center justify-between border-t border-ejo-border pt-4"><Link to={`/app/ibiganiro/${a.id}`} className="inline-flex items-center gap-1 text-xs font-bold text-ejo-blue hover:text-ejo-green">{t('mywork.talk')} {p.name}<ChevronRight size={14}/></Link><span className="flex items-center gap-1.5 text-[10px] text-ejo-muted"><MessageSquareText size={12} className="text-ejo-green"/>{t('mywork.own')}</span></div></article>; })}</section><p className="mt-8 text-[10px] leading-4 text-ejo-muted">{t('mywork.demoNote')}</p></main>;
}