import { ArrowLeft, Check, CircleAlert, FileText, HeartPulse, MessageSquareText, Search, Send, Sparkles } from 'lucide-react';
import { motion } from 'framer-motion'; import { useEffect, useState } from 'react'; import { Link, useNavigate, useParams } from 'react-router-dom';
import { ProviderLogo } from '../components/providers/ProviderLogo';
import { mockProviderService } from '../services/mock/mockProviderService';
import type { Provider } from '../types';
const categories = [
  { name: 'Ubuzima n’imibereho', detail: 'Mutuelle n’izindi serivisi z’umuryango', icon: HeartPulse },
  { name: 'Inyandiko', detail: 'Saba cyangwa urebe serivisi z’inyandiko', icon: FileText },
  { name: 'Gushaka serivisi', detail: 'Tubwire icyo ushaka, tukuyobore', icon: Search },
];
const actions = ['Mutuelle', "Kureba status y'ubusabe", 'Gushaka serivisi', 'Kwemeza ubwishyu'];
const path = ['Sobanukirwa', 'Amakuru', 'Isuzuma', 'Emeza', 'Byarangiye'];

function IremboWorkspace() {
  const [request, setRequest] = useState(''); const [sent, setSent] = useState(false); const [selectedAction, setSelectedAction] = useState<string | null>(null);
  function start(text: string) { setRequest(text); setSelectedAction(text); setSent(false); }
  function send() { if (request.trim()) setSent(true); }
  return <div className="mt-7 grid gap-7 lg:grid-cols-[minmax(0,1fr)_260px]"><section>
    <p className="eyebrow">AHO WAKORERA KURI IREMBO</p>
    <div className="mt-3 grid gap-3 md:grid-cols-3">{categories.map(({ name, detail, icon: Icon }) => <button key={name} onClick={() => start(name === 'Ubuzima n’imibereho' ? 'Ndashaka kwishyurira umuryango wanjye Mutuelle.' : name)} className="border border-ejo-border bg-white p-4 text-left transition-colors hover:border-ejo-green focus-visible:outline focus-visible:outline-2 focus-visible:outline-ejo-green"><Icon size={21} className="text-ejo-blue"/><strong className="mt-6 block font-display text-sm">{name}</strong><small className="mt-1 block text-[10px] leading-4 text-ejo-muted">{detail}</small></button>)}</div>
    <section className="mt-8"><p className="eyebrow">IBYIFUZO BISANZWE</p><div className="mt-3 flex flex-wrap gap-2">{actions.map(action => <button onClick={() => start(action === 'Mutuelle' ? 'Ndashaka kwishyurira umuryango wanjye Mutuelle.' : action)} key={action} className={`border px-3 py-2 text-xs font-semibold ${selectedAction === action ? 'border-ejo-green bg-[#f1f7f4] text-ejo-green' : 'border-ejo-border bg-white text-ejo-blue hover:border-ejo-green'}`}>{action}</button>)}</div></section>
    <section className="mt-8 border border-ejo-border bg-white"><div className="border-b border-ejo-border px-5 py-4"><p className="eyebrow">IKIGANIRO CYA SERIVISI</p><h3 className="font-display text-base font-bold">Ushaka gukora iki?</h3></div><div className="min-h-44 px-5 py-5"><div className="flex gap-3"><span className="grid size-7 place-items-center rounded-full bg-ejo-green font-display font-bold text-white">e</span><div><strong className="text-xs">EjoFlow</strong><p className="mt-1 max-w-md border border-ejo-border bg-ejo-canvas p-3 text-xs leading-5">Muraho. Sobanuza icyo ushaka gukora kuri Irembo; nzakuyobora intambwe ku yindi.</p></div></div>{sent && <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="ml-auto mt-5 max-w-md bg-ejo-blue p-3 text-xs leading-5 text-white">{request}</motion.div>}{sent && <div className="mt-5 flex gap-2 border-l-[3px] border-ejo-green bg-[#f1f7f4] p-3 text-xs leading-5 text-[#285849]"><Check className="shrink-0 text-ejo-green" size={17}/><p><strong>Ndabyumvise.</strong> Reka mbanze menye amakuru make ku muryango wawe.</p></div>}</div><div className="border-t border-ejo-border p-3"><label className="flex items-end gap-2 border border-[#a9bdb6] border-l-[3px] border-l-ejo-green p-2"><textarea value={request} onChange={e => { setRequest(e.target.value); setSent(false); }} rows={2} placeholder="Andika icyo ushaka gukora…" className="w-full resize-none bg-transparent text-xs outline-none"/><button onClick={send} disabled={!request.trim()} aria-label="Ohereza" className="grid size-8 shrink-0 place-items-center bg-ejo-green text-white disabled:cursor-not-allowed disabled:bg-[#a8b8b3]"><Send size={15}/></button></label></div></section>
    <section className="mt-8 border-t border-ejo-border pt-5"><p className="eyebrow">IBIKORWA BIHERUKA</p><h3 className="font-display text-base font-bold">Aho wari ugeze</h3><div className="mt-3 border border-ejo-border bg-white p-4 text-xs"><span className="font-bold text-ejo-blue">Mutuelle</span><span className="mx-2 text-ejo-muted">·</span><span className="text-ejo-muted">Nta gikorwa giheruka kuri Irembo.</span></div></section>
  </section><aside><p className="eyebrow">URUGENDO RWA SERIVISI</p><h3 className="font-display text-base font-bold">Uko bigenda</h3><ol className="mt-5">{path.map((step, index) => { const active = sent ? index === 1 : index === 0; const done = sent && index === 0; return <li className="relative flex min-h-14 gap-3 after:absolute after:left-[13px] after:top-7 after:h-6 after:w-px after:bg-ejo-border last:after:hidden" key={step}><span className={`grid size-7 place-items-center rounded-full border text-[11px] font-bold ${done ? 'border-ejo-green bg-ejo-green text-white' : active ? 'border-ejo-green bg-[#f1f7f4] text-ejo-green ring-4 ring-[#dcece5]' : 'border-[#bfcfca] bg-white text-ejo-muted'}`}>{done ? <Check size={13}/> : index + 1}</span><span><strong className="block text-xs">{step}</strong><small className="block text-[10px] text-ejo-muted">{active ? 'Ubu ni ho uri' : index === 3 ? 'Fata icyemezo' : 'Tuzakuyobora'}</small></span>{index === 3 && !sent && <CircleAlert className="ml-auto text-ejo-amber" size={15}/>}</li>; })}</ol><div className="mt-7 border-t border-ejo-border pt-4 text-[10px] leading-4 text-ejo-muted"><strong className="text-ejo-ink">EjoFlow irasobanura</strong><br/>Uzabona ibyo dukeneye n’impamvu mbere yo gukomeza.</div></aside></div>;
}

function OtherWorkspace({ provider }: { provider: Provider }) {
  const navigate = useNavigate();
  return <div className="mt-7 grid gap-7 lg:grid-cols-[minmax(0,1fr)_260px]"><section>
    <p className="eyebrow">UBUSHOBOZI BW’AKA MURYANGO</p>
    <div className="mt-3 grid gap-3 md:grid-cols-3">{provider.capabilities.length ? provider.capabilities.map(cap => <div key={cap.id} className="border border-ejo-border bg-white p-4"><Sparkles size={21} className="text-ejo-green"/><strong className="mt-6 block font-display text-sm">{cap.name}</strong><small className="mt-1 block text-[10px] leading-4 text-ejo-muted">Turakubwira intambwe ku yindi.</small></div>) : <div className="border border-dashed border-[#b9c9c4] bg-white p-6 text-xs leading-5 text-ejo-muted">Aka muryango uracyari mu buryo bwo kuhuza. Reba nyuma.</div>}</div>
    <section className="mt-8 border border-ejo-border bg-white"><div className="border-b border-ejo-border px-5 py-4"><p className="eyebrow">KUGANIRA NA {provider.name.toUpperCase()}</p><h3 className="font-display text-base font-bold">Ushaka kuganira na {provider.name}?</h3></div><div className="p-5"><div className="flex gap-3"><ProviderLogo id={provider.id} mark={provider.mark} website={provider.website} size="sm"/><div><strong className="text-xs">{provider.name}</strong><p className="mt-1 max-w-md border border-ejo-border bg-ejo-canvas p-3 text-xs leading-5">Muraho! Ni {provider.name}. EjoFlow izafasha kuganira n’iyi serivisi nk’uko ukinira WhatsApp cyangwa email.</p></div></div><div className="mt-5 flex flex-wrap items-center gap-3 border-t border-ejo-border pt-5"><button onClick={() => navigate(`/app/ibiganiro/${provider.id}`)} className="inline-flex items-center gap-2 bg-ejo-green px-4 py-3 text-xs font-bold text-white"><MessageSquareText size={14}/> Tangira ikiganiro na {provider.name}</button><span className="text-[10px] leading-4 text-ejo-muted">Ubu ikiganiro kikorwa na mock; EjoChat API izasimbura.</span></div></div></section>
    <section className="mt-8 border-t border-ejo-border pt-5"><p className="eyebrow">IBIKORWA BIHERUKA</p><h3 className="font-display text-base font-bold">Aho wari ugeze</h3><div className="mt-3 border border-ejo-border bg-white p-4 text-xs"><span className="font-bold text-ejo-blue">{provider.name}</span><span className="mx-2 text-ejo-muted">·</span><span className="text-ejo-muted">Nta gikorwa giheruka.</span></div></section>
  </section><aside><p className="eyebrow">URUGENDO RWA SERIVISI</p><h3 className="font-display text-base font-bold">Uko bigenda</h3><ol className="mt-5">{path.map((step, index) => <li className="relative flex min-h-14 gap-3 after:absolute after:left-[13px] after:top-7 after:h-6 after:w-px after:bg-ejo-border last:after:hidden" key={step}><span className="grid size-7 place-items-center rounded-full border border-[#bfcfca] bg-white text-[11px] font-bold text-ejo-muted">{index + 1}</span><span><strong className="block text-xs">{step}</strong><small className="block text-[10px] text-ejo-muted">Tuzakuyobora</small></span></li>)}</ol><div className="mt-7 border-t border-ejo-border pt-4 text-[10px] leading-4 text-ejo-muted"><strong className="text-ejo-ink">Ugenzura intambwe zose</strong><br/>Nta kintu kirangira utabyemeje.</div></aside></div>;
}

export function ProviderWorkspacePage() {
  const { providerId = 'irembo' } = useParams();
  const [provider, setProvider] = useState<Provider | null>(null); const [missing, setMissing] = useState(false);
  useEffect(() => { let alive = true; mockProviderService.getById(providerId).then(p => { if (!alive) return; if (!p) { setMissing(true); return; } setProvider(p); }); return () => { alive = false; }; }, [providerId]);
  return <main className="mx-auto max-w-[1180px] px-4 py-8 md:px-10 md:py-10"><Link to="/app" className="mb-6 inline-flex items-center gap-1 text-xs font-bold text-ejo-blue hover:text-ejo-green"><ArrowLeft size={15}/> Serivisi zanjye</Link>
    {missing ? <section className="border border-dashed border-[#b9c9c4] bg-white p-8 text-center"><CircleAlert className="mx-auto text-ejo-amber" size={22}/><h2 className="mt-3 font-display text-lg font-bold">Ntabwo umuyoboro ubonetse</h2><p className="mt-1 text-xs text-ejo-muted">Iyo serivisi ntiboneka. Gerageza irindi.</p></section> : !provider ? <WorkspaceLoading/> : <><header className="border-t-[3px] border-ejo-blue bg-white px-5 py-5 md:flex md:items-end md:justify-between"><div className="flex items-center gap-3"><ProviderLogo id={provider.id} mark={provider.mark} website={provider.website} size="lg"/><div><p className="eyebrow mb-1">{provider.domain.toUpperCase()} · {provider.website?.toUpperCase()}</p><h2 className="font-display text-2xl font-bold">{provider.name}</h2><p className="mt-1 text-xs text-ejo-muted">{provider.description}</p></div></div><span className="mt-4 inline-flex items-center gap-1 text-[10px] font-bold text-ejo-green md:mt-0"><span className="size-2 rounded-full bg-ejo-green"/> Bihujwe kandi byiteguye</span></header>
      {provider.id === 'irembo' ? <IremboWorkspace/> : <OtherWorkspace provider={provider}/>}
    </>}</main>;
}
function WorkspaceLoading() { return <><div className="mt-6 h-28 animate-pulse border border-ejo-border bg-white"/><div className="mt-6 grid gap-3 md:grid-cols-3"><div className="h-40 animate-pulse border border-ejo-border bg-white"/><div className="h-40 animate-pulse border border-ejo-border bg-white"/><div className="h-40 animate-pulse border border-ejo-border bg-white"/></div><div className="mt-6 h-72 animate-pulse border border-ejo-border bg-white"/></>; }