import { Search } from 'lucide-react'; import { useEffect, useMemo, useState } from 'react'; import { useNavigate } from 'react-router-dom';
import { ProviderCard } from '../components/providers/ProviderCard';
import { ProviderMarquee } from '../components/providers/ProviderMarquee';
import { providerService } from '../services/providerService';
import type { Provider, ProviderCategory } from '../types';
const categoryFilters: [ProviderCategory | 'all', string][] = [['all', 'Byose'], ['government', 'Leta'], ['communication', 'Ibiganiro'], ['business', 'Ubucuruzi'], ['personal', 'Ku giti cye'], ['ai', 'AI']];
export function ProviderDashboardPage() {
  const [providers, setProviders] = useState<Provider[]>([]); const [category, setCategory] = useState<ProviderCategory | 'all'>('all'); const [query, setQuery] = useState('');
  const navigate = useNavigate();
  useEffect(() => { providerService.list().then(setProviders); }, []);
  const visible = useMemo(() => providers.filter(provider => (category === 'all' || provider.category === category) && (provider.name.toLowerCase().includes(query.toLowerCase()) || provider.domain.toLowerCase().includes(query.toLowerCase()) || provider.description.toLowerCase().includes(query.toLowerCase()))), [providers, category, query]);
  const select = (provider: Provider) => { navigate('/app/serivisi/' + provider.id); };
  return <main className="mx-auto max-w-[1200px] px-4 py-8 md:px-10 md:py-12"><div className="mb-8 max-w-2xl"><p className="eyebrow">AHO WAKORERA</p><h2 className="font-display text-2xl font-bold tracking-tight md:text-[28px]">Ni uwo nde ushaka kuganira?</h2><p className="mt-2 max-w-xl leading-6 text-ejo-muted">Hitamo umuyoboro ukoresheje ikirango n'izina — nk'uko uhitamo umuntu wizeye. EjoFlow izakora n'uwatoranyijwe.</p></div>{providers.length > 0 && <ProviderMarquee providers={providers} onSelect={select}/>}<section className="mt-9"><div className="section-heading"><div><p className="eyebrow">SERIVISI ZANJYE ZIHUJE</p><h3>Hitamo uwo tuganira na we</h3></div><label className="flex w-44 items-center gap-1 border-b border-[#91a8a1] pb-1 text-ejo-green focus-within:border-ejo-blue"><Search size={15}/><input value={query} onChange={event => setQuery(event.target.value)} aria-label="Shaka serivisi" placeholder="Shaka serivisi..." className="w-full bg-transparent text-xs outline-none"/></label></div><div className="flex flex-wrap gap-2 border-y border-ejo-border py-3" aria-label="Shungura serivisi z'ubwoko">{categoryFilters.map(([value, label]) => <button onClick={() => setCategory(value)} key={value} className={`border px-3 py-2 text-xs font-bold ${category === value ? 'border-ejo-green bg-[#f1f7f4] text-ejo-green' : 'border-ejo-border bg-white text-ejo-blue hover:border-ejo-green'}`}>{label}</button>)}</div>{visible.length ? <div className="mt-5 grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">{visible.map(provider => <ProviderCard provider={provider} selected={false} onSelect={select} key={provider.id}/>)}</div> : <div className="mt-5 border border-dashed border-[#b9c9c4] bg-white p-8 text-center"><Search className="mx-auto text-ejo-green"/><h4 className="mt-2 font-display font-bold">Nta serivisi ubonye</h4><p className="mt-1 text-xs text-ejo-muted">Gerageza irindi zina cyangwa usibe akayunguruzo.</p><button onClick={() => { setQuery(''); setCategory('all'); }} className="mt-3 border border-ejo-blue px-3 py-2 text-xs font-bold text-ejo-blue">Siba ishakisha</button></div>}</section></main>;
}